# Timestream + Grafana compose file. 
# With data persistency
version: '3'

services:
  timestream:
    image: timestream:1.7
    container_name: timestream
    ports:
      - "8086:8086"
      - "2003:2003"
    environment:
      timestream_ADMIN_USER: admin
      timestream_ADMIN_PASSWORD: pass
      timestream_HTTP_AUTH_ENABLED: "false"
      timestream_GRAPHITE_ENABLED: "false"
    volumes:
      - /var/lib/docker/volumes:/var/lib/timestream

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: "0"
    links:
      - timestream
    volumes:
      - /var/lib/docker/volumes:/var/lib/grafana

  chronograf:
      image: chronograf:latest
      links:
      - timestream
      volumes:
      - /var/lib/docker/volumes:/var/lib/grafana
      ports:
      - "8087:8888"