# Timestream + Grafana compose file. 
# With data persistency
version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: "0"
    links:
      - timestream
    volumes:
      - /var/lib/docker/volumes:/var/lib/grafana
