{
 "title": "Locust Dashboard With Working",
 "tags": [ "locust" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "DB_SOURCE", "label": "DB_SOURCE", "query": "timestream" }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Requests",
   "type": "gauge",
   "description": "Current Requests Per Second",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(counter)\nFROM \"locust_requests\"\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "description": "Total Success requests",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"success\" = 'True'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real Fail",
   "type": "singlestat",
   "description": "Total unhandled errors",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"success\" = 'False'\nAND \"exception\" !~ /invalid-path*/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Detailed Response Time per Endpoint",
   "type": "table",
   "description": "Number of requests per second over time.",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "alias": "$tag_request_type $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"time\", \"response_time\"\nFROM \"locust_requests\"\nWHERE $timeFilter\nGROUP BY \"request_type\", \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fake Fail",
   "type": "singlestat",
   "description": "Total fake failure requests",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"success\" = 'False'\nAND \"exception\" =~ /invalid-path*/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Response Time Over TIme",
   "type": "graph",
   "description": "Number of requests per second over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_request_type $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"time\", \"response_time\"\nFROM \"locust_requests\"\nWHERE $timeFilter\nGROUP BY \"request_type\", \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests Per Second Over Time",
   "type": "graph",
   "description": "Number of requests per second over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_request_type $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"time\", count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter\nGROUP BY time(1s), \"request_type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hatching Events",
   "type": "table",
   "description": "Hatching Events",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"time\", \"event\", \"node_id\", \"user_count\"\nFROM \"locust_events\" \nWHERE $timeFilter\nAND event <> 'papaya'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "alias": "$tag_request_type $tag_name: $tag_exception",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND exception <> 'None'\nGROUP BY \"request_type\", \"name\", \"exception\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Locust Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"exception\")\nFROM \"locust_exceptions\" \nWHERE $timeFilter\nGROUP BY \"exception_tag\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}